service: todos-demo

frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: '20201221'

custom:
  DB_PREFIX: ${file(./conf/config.yml):${self:provider.stage}.DB_PREFIX}

package:
  patterns:
    - '!./**'
    - 'src/**'
    - 'node_modules/**'

functions:
  getAllTodos:
    handler: src/handler.getAllTodos
    events:
      - http:
          method: GET
          path: todos/getAll
          cors: true

  createTodo:
    handler: src/handler.createTodo
    events:
      - http:
          method: POST
          path: todos
          cors: true

  updateTodo:
    handler: src/handler.updateTodo
    events:
      - http:
          method: PUT
          path: todos/update
          cors: true

  updateTodoStatus:
    handler: src/handler.updateTodoStatus
    events:
      - http:
          method: PUT
          path: todos/status
          cors: true
  
  deleteTodo:
    handler: src/handler.deleteTodo
    events:
      - http:
          method: DELETE
          path: todos/delete/{id}
          cors: true